# Generated by Django 4.1.5 on 2023-01-24 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='fichie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_f', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Madjmo3at',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_m', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_w', models.CharField(max_length=300)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.fichie')),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_ype', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=300)),
                ('paragraph', models.TextField(default='paragrpahe')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.article')),
            ],
        ),
        migrations.AddField(
            model_name='fichie',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.madjmo3at'),
        ),
    ]
